language: python
python:
  - "3.6"
# command to install dependencies
before_install:
#  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
#  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6"
#  - "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list"
#  - "echo 'deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse' | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list"
#  - "sudo apt-get update"
  - "sudo apt-get install mongodb-org-server"
install: "pip install -r deployment/requirements/dev.txt"
# command to run tests
before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
script: py.test
